### PR TITLE
Update Host_IO-Win.cpp

### PR DESCRIPTION
**Pull request by Jamaika1**

### CODE REVIEW

**Comment by hfiguiere** [comment]
I don't understand what you are trying to do here.

**Comment by Jamaika1** [comment]
I use gcc 7.1 and compiling adobe dng sdk 1.4 with xmp sdk. I have a message.
_Host_IO-Win.cpp: In function 'bool Host_IO::GetNextChild(Host_IO::FolderRef, std::__cxx11::string*)':
Host_IO-Win.cpp:538:52: error: cannot convert 'WIN32_FIND_DATAW* {aka _WIN32_FIND_DATAW*}' to 'LPWIN32_FIND_DATAA {aka _WIN32_FIND_DATAA*}' for argument '2' to 'WINBOOL FindNextFileA(HANDLE, LPWIN32_FIND_DATAA)'
   found = (bool) FindNextFile ( folder, &childInfo );_

I delete line _found = (bool) FindNextFile ( folder, &childInfo );_

**Comment by hfiguiere** [comment]
Deleting a line isn't a solution.

Again, Exempi isn't supported on Windows. 

However I would accept a proper pull request to build it properly on Windows.

**Comment by hfiguiere** [comment]
>  compiling adobe dng sdk 1.4 with xmp sdk.

This is not the XMP_SDK. If it says to use the XMP_SDK, get XMP_SDK from Adobe.

**Pull request closed without merging**
